#########################################################################
# Title:            Community: N8n                                   #
# Author(s):        tarek                                               #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  n8nio/n8n                                           #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: MariaDB Role
  include_role:
    name: mariadb

- name: "sleep for 20 seconds and continue"
  wait_for: timeout=20

- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: n8n
  when: cloudflare_enabled

- name: Stop and remove any existing containers
  docker_container: "name={{ item }} state=absent"
  with_items:
    - n8n

- name: Create n8n directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/n8n

- name: Create and start n8n container
  docker_container:
    name: n8n
    image: "n8nio/n8n"
    pull: yes
    published_ports:
      - "5678:5678"
    env:
      TZ: "{{ tz }}"
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      DB_MYSQLDB_HOST: "mariadb"
      DB_MYSQLDB_DATABASE: "n8n"
      DB_MYSQLDB_USER: "root"
      DB_MYSQLDB_PASSWORD: "password321"
      VIRTUAL_HOST: "n8n.{{ user.domain }}"
      VIRTUAL_PORT: "5678"
      LETSENCRYPT_HOST: "n8n.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "{{ user.name }}"
      N8N_BASIC_AUTH_PASSWORD: "{{ user.pass }}"
    volumes:
      - "/mnt:/mnt"
      - "/opt/n8n:/root/.n8n"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - huginn
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
