#########################################################################
# Title:            Community: shlink                                  #
# Author(s):        atilling                                            #
# URL:              https://github.com/Cloudbox/Community               #
# Docker Image(s):  shlinkio/shlink                                     #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Setting CloudFlare DNS Record"
  include_role:
    name: cloudflare-dns
  vars:
    record: shlink
  when: cloudflare_enabled

- name: Stop and remove any existing container
  docker_container:
    name: shlink
    state: absent

- name: Create shlink directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/shlink

- name: Create and start container
  docker_container:
    name: shlink
    image: shlinkio/shlink:stable
    pull: yes
    published_ports:
      - "127.0.0.1:8080:8080"
    env:
      TZ: "{{ tz }}"
      USER_ID: "{{ uid }}"
      GROUP_ID: "{{ gid }}"
      VIRTUAL_HOST: "shlink.{{ user.domain }}"
      VIRTUAL_PORT: "8080"
      LETSENCRYPT_HOST: "shlink.{{ user.domain }}"
      LETSENCRYPT_EMAIL: "{{ user.email }}"
      SHORT_DOMAIN_SCHEMA: "https"
      SHORT_DOMAIN_HOST: "shlink.{{ user.domain }}"
      GEOLITE_LICENSE_KEY: "kjh23ljkbndskj345"
    volumes:
      - "/opt/shlink:/etc/shlink/config/params"
      - "/mnt:/mnt"
    labels:
      "com.github.cloudbox.cloudbox_managed": "true"
    networks:
      - name: cloudbox
        aliases:
          - shlink
    purge_networks: yes
    restart_policy: unless-stopped
    state: started
